export const driveLabels = {
  clearSearch: "Clear search",
  title: "Drive",
  description: "Files and folders linked to your workspace records.",
  spaces: "Drive spaces",
  searchSpaces: "Search spaces",
  searchFiles: "Search this folder",
  emptySpaces: "No spaces found.",
  empty: "This folder is empty.",
  noMatches: "No matching files or folders.",
  loading: "Loading…",
  error: "The operation failed. Please try again.",
  retry: "Retry",
  back: "Back to drive",
  root: "All files",
  breadcrumbs: "Folder navigation",
  navigation: "Drive navigation",
  closeNavigation: "Close Drive navigation",
  expandFolder: "Expand folder",
  collapseFolder: "Collapse folder",
  loadMoreFolders: "Load more folders",
  name: "Name",
  size: "Size",
  modified: "Modified",
  owner: "Owner",
  unavailable: "—",
  actions: "Actions",
  folder: "Folder",
  upload: "Upload files",
  newFolder: "New folder",
  rename: "Rename",
  delete: "Delete",
  download: "Download",
  cancel: "Cancel",
  close: "Close",
  save: "Save",
  create: "Create",
  next: "Next page",
  first: "First page",
  previous: "Previous page",
  readOnly: "Read-only",
  drop: "Drop files here or choose Upload files.",
  pending: "Please wait…",
  saved: "Changes saved.",
  deleted: "Files and folders deleted.",
  trash: "Trash",
  searchTrash: "Search trash",
  emptyTrash: "Trash is empty. Deleted files and folders appear here until their expiry date.",
  moveToTrash: "Move to trash",
  trashTitle: "Move files and folders to trash",
  trashed: "Files and folders moved to trash.",
  undo: "Undo",
  undoConflict: "Open Trash to choose a folder or another name for this item.",
  restore: "Restore",
  restoring: "Restoring…",
  restored: "Files and folders restored.",
  restoreTitle: "Restore files and folders",
  restoreDescription: "Choose a folder and an available name. Existing files are never replaced.",
  destination: "Destination folder",
  originalFolder: "Original folder",
  originalLocation: "Original location",
  deletedAt: "Deleted",
  expiresAt: "Expires",
  trashHint: "Restore items before their expiry date. Permanent deletion cannot be undone.",
  trashDescription: (name: string, files: number, folders: number) =>
    `Move ${name}, including ${files} file(s) and ${folders} folder(s), to trash? You can restore them before their expiry date.`,
  trashConfirmation: (name: string) =>
    `Move ${name} to trash? You can restore it before its expiry date.`,
  downloading: "Download started.",
  uploads: "Uploads",
  queued: "Queued",
  uploading: "Uploading",
  finishing: "Finalizing",
  done: "Uploaded",
  failed: "Failed",
  cancelled: "Cancelled",
  cancelling: "Cancelling",
  cancelFailed: "Cancellation needs a retry.",
  dismiss: "Dismiss",
  deleting: "Deletion pending",
  deleteTitle: "Delete files and folders",
  confirmDelete: "Delete permanently",
  nameHint: "Enter a name without slashes.",
  uploadLimit: (bytes: number) => `Maximum file size: ${Math.round(bytes / 1_000_000)} MB.`,
  deleteDescription: (name: string, files: number, folders: number) =>
    `Permanently delete ${name}, including ${files} file(s) and ${folders} folder(s)? This cannot be undone.`,
  deleteConfirmation: (name: string) => `Permanently delete ${name}? This cannot be undone.`,
  progress: (name: string) => `Upload progress for ${name}`,
  openRecord: "Open linked record",
  folderDrop: "Folder uploads are not supported. Select files instead.",
  INVALID: "Check the name, file size, or input and try again.",
  NOT_FOUND: "This space or item is no longer available.",
  FORBIDDEN: "You no longer have permission for this action.",
  CONFLICT: "The folder changed or this name is already used. Refresh and try again.",
  RESTORE_CONFLICT:
    "The original folder is unavailable or the name is already used. Choose a folder or another name.",
  EXPIRED: "This upload expired. Select the file again.",
  DELETE_PENDING: "Deletion is incomplete. Retry to finish removing the remaining contents.",
  STORAGE: "Storage is unavailable. Please retry.",
};
export type DriveLabels = typeof driveLabels;
