export const driveLabels = {
  title: "Drive",
  description: "Files and folders linked to your workspace records.",
  spaces: "Drive spaces",
  searchSpaces: "Search spaces",
  searchFiles: "Search this folder",
  emptySpaces: "No spaces found.",
  empty: "This folder is empty.",
  noMatches: "No matching files or folders.",
  loading: "Loading…",
  error: "The operation failed. Please try again.",
  retry: "Retry",
  back: "Back to Drive",
  root: "All files",
  breadcrumbs: "Folder navigation",
  name: "Name",
  size: "Size",
  modified: "Modified",
  actions: "Actions",
  folder: "Folder",
  upload: "Upload files",
  newFolder: "New folder",
  rename: "Rename",
  delete: "Delete",
  download: "Download",
  cancel: "Cancel",
  close: "Close",
  save: "Save",
  create: "Create",
  next: "Next page",
  first: "First page",
  readOnly: "Read only",
  drop: "Drop files here or choose Upload files.",
  pending: "Please wait…",
  saved: "Changes saved.",
  deleted: "Deletion completed.",
  downloading: "Download started.",
  uploads: "Uploads",
  queued: "Queued",
  uploading: "Uploading",
  finishing: "Finalizing",
  done: "Uploaded",
  failed: "Failed",
  cancelled: "Cancelled",
  cancelling: "Cancelling",
  cancelFailed: "Cancellation needs a retry.",
  dismiss: "Dismiss",
  deleting: "Deletion pending",
  deleteTitle: "Delete files and folders",
  confirmDelete: "Delete permanently",
  nameHint: "Enter a name without slashes.",
  uploadLimit: (bytes: number) => `Maximum file size: ${Math.round(bytes / 1_000_000)} MB.`,
  deleteDescription: (name: string, files: number, folders: number) =>
    `Permanently delete ${name}, including ${files} file(s) and ${folders} folder(s)? This cannot be undone.`,
  progress: (name: string) => `Upload progress for ${name}`,
  openRecord: "Open linked record",
  folderDrop: "Folder uploads are not supported. Select files instead.",
  INVALID: "Check the name, file size, or input and try again.",
  NOT_FOUND: "This space or item is no longer available.",
  FORBIDDEN: "You no longer have permission for this action.",
  CONFLICT: "The folder changed or this name is already used. Refresh and try again.",
  EXPIRED: "This upload expired. Select the file again.",
  DELETE_PENDING: "Deletion is incomplete. Retry to finish removing the remaining contents.",
  STORAGE: "Storage is unavailable. Please retry.",
};
export type DriveLabels = typeof driveLabels;
