allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.3
  vitest: 4.1.11
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
