import { defineConfig } from "vite-plus";

// Vite Plus provides code quality tools; Next.js still runs the showroom.
export default defineConfig({
  fmt: {
    tabWidth: 2,
    semi: true,
    printWidth: 100,
    singleQuote: false,
    endOfLine: "lf",
    trailingComma: "all",
    sortImports: {},
    sortTailwindcss: {
      stylesheet: "./src/styles/globals.css",
      attributes: ["class", "className"],
      functions: ["clsx", "cn", "cva", "tw"],
    },
    sortPackageJson: true,
    ignorePatterns: [
      "public/r/**",
      "pnpm-lock.yaml",
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      "next-env.d.ts",
    ],
  },
  lint: {
    plugins: ["typescript", "react", "jsx-a11y", "nextjs"],
    env: { builtin: true, node: true, browser: true },
    options: { typeAware: true, typeCheck: true },
    jsPlugins: [{ name: "react-hooks-js", specifier: "eslint-plugin-react-hooks" }],
    rules: {
      "no-unused-vars": "warn",
      "no-unused-expressions": "warn",
      "typescript/ban-ts-comment": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-empty-object-type": "error",
      "react/jsx-key": "error",
      "react/jsx-no-duplicate-props": "error",
      "react/no-danger-with-children": "error",
      "react/no-unescaped-entities": "error",
      "react/rules-of-hooks": "error",
      "react/exhaustive-deps": "warn",
      // Keep React compiler checks from the previous Next.js ESLint preset.
      "react-hooks-js/config": "error",
      "react-hooks-js/error-boundaries": "error",
      "react-hooks-js/gating": "error",
      "react-hooks-js/globals": "error",
      "react-hooks-js/immutability": "error",
      "react-hooks-js/incompatible-library": "warn",
      "react-hooks-js/preserve-manual-memoization": "error",
      "react-hooks-js/purity": "error",
      "react-hooks-js/refs": "error",
      "react-hooks-js/set-state-in-effect": "error",
      "react-hooks-js/set-state-in-render": "error",
      "react-hooks-js/static-components": "error",
      "react-hooks-js/unsupported-syntax": "warn",
      "react-hooks-js/use-memo": "error",
      "jsx-a11y/alt-text": ["warn", { elements: ["img"], img: ["Image"] }],
      "jsx-a11y/aria-props": "warn",
      "jsx-a11y/aria-proptypes": "warn",
      "jsx-a11y/aria-unsupported-elements": "warn",
      "jsx-a11y/role-has-required-aria-props": "warn",
      "jsx-a11y/role-supports-aria-props": "warn",
      // Native equivalents of Next.js core-web-vitals rules.
      "nextjs/google-font-display": "warn",
      "nextjs/google-font-preconnect": "warn",
      "nextjs/next-script-for-ga": "warn",
      "nextjs/no-async-client-component": "warn",
      "nextjs/no-before-interactive-script-outside-document": "warn",
      "nextjs/no-css-tags": "warn",
      "nextjs/no-head-element": "warn",
      "nextjs/no-html-link-for-pages": "error",
      "nextjs/no-img-element": "warn",
      "nextjs/no-page-custom-font": "warn",
      "nextjs/no-styled-jsx-in-document": "warn",
      "nextjs/no-sync-scripts": "error",
      "nextjs/no-title-in-document-head": "warn",
      "nextjs/no-typos": "warn",
      "nextjs/no-unwanted-polyfillio": "warn",
      "nextjs/inline-script-id": "error",
      "nextjs/no-assign-module-variable": "error",
      "nextjs/no-document-import-in-page": "error",
      "nextjs/no-duplicate-head": "error",
      "nextjs/no-head-import-in-document": "error",
      "nextjs/no-script-component-in-head": "error",
    },
    ignorePatterns: [
      "public/r/**",
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      "next-env.d.ts",
    ],
  },
});
