import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import react from "@vitejs/plugin-react";
import { nitro } from "nitro/vite";
import { defineConfig } from "vite-plus";

export default defineConfig({
  server: { port: 3000 },
  resolve: { tsconfigPaths: true },
  plugins: [tanstackStart(), nitro({ preset: "node-server" }), react(), tailwindcss()],
  fmt: {
    tabWidth: 2,
    semi: true,
    printWidth: 100,
    singleQuote: false,
    endOfLine: "lf",
    trailingComma: "all",
    sortImports: {},
    sortTailwindcss: {
      stylesheet: "./src/styles/globals.css",
      attributes: ["class", "className"],
      functions: ["clsx", "cn", "cva", "tw"],
    },
    sortPackageJson: true,
    ignorePatterns: [
      ".agents/**",
      "public/r/**",
      "pnpm-lock.yaml",
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      ".output/**",
      ".tanstack/**",
      "dist/**",
      "src/routeTree.gen.ts",
    ],
  },
  lint: {
    plugins: ["typescript", "react", "jsx-a11y"],
    env: { builtin: true, node: true, browser: true },
    options: { typeAware: true, typeCheck: true },
    jsPlugins: [{ name: "react-hooks-js", specifier: "eslint-plugin-react-hooks" }],
    rules: {
      "no-unused-vars": "warn",
      "no-unused-expressions": "warn",
      "typescript/ban-ts-comment": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-empty-object-type": "error",
      "react/jsx-key": "error",
      "react/jsx-no-duplicate-props": "error",
      "react/no-danger-with-children": "error",
      "react/no-unescaped-entities": "error",
      "react/rules-of-hooks": "error",
      "react/exhaustive-deps": "warn",
      // Preserve the existing React compiler checks.
      "react-hooks-js/config": "error",
      "react-hooks-js/error-boundaries": "error",
      "react-hooks-js/gating": "error",
      "react-hooks-js/globals": "error",
      "react-hooks-js/immutability": "error",
      "react-hooks-js/incompatible-library": "warn",
      "react-hooks-js/preserve-manual-memoization": "error",
      "react-hooks-js/purity": "error",
      "react-hooks-js/refs": "error",
      "react-hooks-js/set-state-in-effect": "error",
      "react-hooks-js/set-state-in-render": "error",
      "react-hooks-js/static-components": "error",
      "react-hooks-js/unsupported-syntax": "warn",
      "react-hooks-js/use-memo": "error",
      "jsx-a11y/alt-text": ["warn", { elements: ["img"], img: ["Image"] }],
      "jsx-a11y/aria-props": "warn",
      "jsx-a11y/aria-proptypes": "warn",
      "jsx-a11y/aria-unsupported-elements": "warn",
      "jsx-a11y/role-has-required-aria-props": "warn",
      "jsx-a11y/role-supports-aria-props": "warn",
    },
    ignorePatterns: [
      "public/r/**",
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      ".output/**",
      ".tanstack/**",
      "dist/**",
      "src/routeTree.gen.ts",
    ],
  },
});
