export const reservationLabels = {
  booking: "Book an appointment",
  accommodation: "Accommodation",
  stayService: "Stay offering",
  stayBooking: "Book a stay",
  stayBook: "Book stay",
  stayAnother: "Book another stay",
  arrivalDate: "Arrival date",
  departureDate: "Departure date",
  arrivalStart: "Earliest arrival",
  arrivalEnd: "Arrival window end (exclusive)",
  checkoutTime: "Checkout time",
  minNights: "Minimum nights",
  maxNights: "Maximum nights",
  nights: "Nights",
  blockedDates: "Blocked dates",
  blockedFrom: "Blocked from",
  blockedThrough: "Blocked through (inclusive)",
  addClosure: "Add closure",
  closuresHelp:
    "Active resources are available continuously except for bookings and blocked dates. Both dates are included in a closure.",
  stayYearHelp:
    "Select a date to open its reservations. Counts include every date a stay occupies, including its checkout day.",
  modeMismatch:
    "The website's booking mode does not match this installation. Contact the administrator.",
  manage: "Manage reservation",
  calendar: "Reservations",
  settings: "Reservation settings",
  service: "Service",
  resource: "Practitioner or resource",
  anyResource: "Any available",
  date: "Date",
  time: "Time",
  previous: "Previous",
  next: "Next",
  today: "Today",
  year: "Year",
  yearHelp:
    "Select a date to open its appointments. Badges show reservation counts. Weekends are shaded.",
  month: "Month",
  week: "Week",
  day: "Day",
  agenda: "Agenda",
  name: "Name",
  email: "Email",
  phone: "Phone (optional)",
  review: "Review booking",
  back: "Back",
  book: "Book appointment",
  booked: "Your reservation has been saved. Check your email for the private management link.",
  another: "Book another appointment",
  duration: "Duration (minutes)",
  timeZone: "Business time zone",
  cancellationDeadline: "Cancel or reschedule before",
  approvalRequired:
    "This reservation requires staff approval. Your time is reserved while you wait.",
  automaticApproval: "This reservation is confirmed automatically.",
  moveWarning:
    "Moving this reservation releases your old time. The new time will need staff approval.",
  pending: "Awaiting approval",
  confirmed: "Confirmed",
  rejected: "Rejected",
  cancelled: "Cancelled",
  cancel: "Cancel reservation",
  cancelConfirm: "Cancel this reservation and release its time?",
  keep: "Keep reservation",
  reschedule: "Reschedule",
  saveMove: "Save new time",
  cutoff: "The change deadline has passed. Contact the business for assistance.",
  approve: "Approve",
  reject: "Reject",
  rejectConfirm: "Reject this request and release its time?",
  close: "Close",
  loading: "Loading…",
  emptySlots: "No available times on this date.",
  emptyServices: "No services are available yet.",
  emptyCalendar: "No reservations in this period.",
  unavailable: "Public booking is currently closed.",
  error: "Something went wrong. Try again.",
  invalid: "Check the entered values and try again.",
  conflict: "This booking or time has changed. Refresh and choose an available time.",
  forbidden: "You do not have permission to perform this action.",
  invalidLink: "This private link is invalid or has expired. Contact the business for a new link.",
  refresh: "Refresh",
  save: "Save",
  saved: "Saved.",
  saving: "Saving…",
  all: "All",
  status: "Status",
  newBooking: "New reservation",
  outsideHours: "Outside current working hours",
  emailFailed: "Email delivery failed",
  retryEmail: "Retry email",
  revokeLink: "Replace private link",
  revokeConfirm: "Invalidate previous management links and email a replacement?",
  retryQueued: "Email delivery queued.",
  business: "Business",
  services: "Services",
  resources: "Resources",
  newService: "New service",
  newResource: "New resource",
  edit: "Edit",
  description: "Description",
  active: "Active",
  archived: "Archived",
  archive: "Archive",
  archiveConfirm: "Archive this item? Existing reservations remain available.",
  publicEnabled: "Allow public booking",
  bufferBefore: "Preparation buffer (minutes)",
  bufferAfter: "Cleanup buffer (minutes)",
  cancellation: "Cancellation notice (minutes)",
  approval: "Approval",
  automatic: "Automatic",
  manual: "Manual",
  notice: "Minimum booking notice (minutes)",
  horizon: "Advance booking limit (days)",
  interval: "Start-time interval (minutes)",
  eligibleResources: "Eligible resources",
  hours: "Weekly working hours",
  exceptions: "Date-specific hours and closures",
  addHours: "Add interval",
  remove: "Remove",
  addException: "Add date",
  closed: "Closed",
  start: "Start",
  end: "End",
  hoursHelp:
    "Use separate intervals for breaks. A date override replaces all weekly hours for that date. Leave it empty to close the date.",
  policyHelp: "Changes apply to new bookings. Existing reservations keep their saved policies.",
  weekday1: "Monday",
  weekday2: "Tuesday",
  weekday3: "Wednesday",
  weekday4: "Thursday",
  weekday5: "Friday",
  weekday6: "Saturday",
  weekday7: "Sunday",
};
export type ReservationLabels = typeof reservationLabels;

export function getReservationLabels(
  overrides: Partial<ReservationLabels> | undefined,
  mode?: "appointment" | "stay",
): ReservationLabels {
  const labels = { ...reservationLabels, ...overrides };
  return mode === "stay"
    ? {
        ...labels,
        booking: labels.stayBooking,
        book: labels.stayBook,
        another: labels.stayAnother,
        yearHelp: labels.stayYearHelp,
        resource: labels.accommodation,
        service: labels.stayService,
      }
    : labels;
}
