export const projectLabels = {
  clearSearch: "Clear search",
  title: "Projects",
  description: "Manage your projects, owners, and assignees.",
  customerDescription: "Projects owned by this customer.",
  create: "Create project",
  newTitle: "New project",
  newDescription: "Add the project name, status, and description.",
  detailsTitle: "Project details",
  detailsDescription: "Update the name, status, and description for this project.",
  back: "Back to projects",
  sections: "Project sections",
  details: "Details",
  drive: "Drive",
  name: "Name",
  status: "Status",
  projectDescription: "Description",
  owner: "Owner",
  assignee: "Assignee",
  website: "Website",
  actions: "Actions",
  requested: "Requested",
  prospect: "Prospect",
  "under-construction": "Under construction",
  production: "Production",
  search: "Search projects",
  searchPlaceholder: "Search projects…",
  loading: "Loading projects…",
  empty: "No projects found.",
  edit: (name: string) => `Edit ${name}`,
  visit: (name: string) => `Visit ${name} website`,
  noWebsite: "No website URL yet",
  unavailableOwner: "Unavailable customer",
  unavailableAssignee: "Unavailable assignee",
  unassigned: "Unassigned",
  nameRequired: "Enter a project name.",
  descriptionInvalid: "Keep the description within 5,000 characters.",
  statusInvalid: "Choose a project status.",
  save: "Save changes",
  pending: "Please wait…",
  saved: "Project updated.",
  created: "Project created.",
  actionError: "The action failed. Please try again.",
  deleteProject: "Delete project",
  deleteDescription: (name: string) => `Delete ${name}? This action cannot be undone.`,
  cancel: "Cancel",
  confirmDelete: "Delete",
  deleted: "Project deleted.",
};

export type ProjectsLabels = typeof projectLabels;
