export const projectLabels = {
  title: "Projects",
  description: "A complete list of all projects.",
  customerDescription: "Projects owned by this customer.",
  create: "Create Project",
  newTitle: "New Project",
  newDescription: "Add the project details and choose a customer owner.",
  detailsTitle: "Project Details",
  detailsDescription: "Update the description, owner, and assignee for this project.",
  back: "Back to Projects",
  sections: "Project sections",
  details: "Details",
  drive: "Drive",
  name: "Name",
  status: "Status",
  projectDescription: "Description",
  url: "Website URL",
  urlPlaceholder: "https://example.com",
  owner: "Owner",
  assignee: "Assignee",
  website: "Website",
  actions: "Actions",
  requested: "Requested",
  prospect: "Prospect",
  "under-construction": "Under Construction",
  production: "Production",
  search: "Search projects",
  searchPlaceholder: "Search projects…",
  loading: "Loading projects…",
  empty: "No projects found.",
  edit: (name: string) => `Edit ${name}`,
  visit: (name: string) => `Visit ${name} website`,
  noWebsite: "No website URL yet",
  unavailableOwner: "Unavailable customer",
  unavailableAssignee: "Unavailable assignee",
  unassigned: "Unassigned",
  selectOwner: "Select an owner",
  selectAssignee: "Select an assignee",
  searchOwners: "Search customers",
  searchAssignees: "Search assignees",
  pickerDescription: "Search by name or email, then choose a person.",
  noMatches: "No matches found.",
  clearAssignee: "Leave unassigned",
  close: "Close",
  customersLoading: "Loading customers…",
  assigneesLoading: "Loading assignees…",
  noCustomers: "Create a customer before creating a project.",
  createCustomer: "Create Customer",
  nameRequired: "Enter a project name.",
  ownerRequired: "Choose an existing customer as owner.",
  assigneeInvalid: "Choose an available assignee or leave this field unassigned.",
  descriptionInvalid: "Keep the description within 5,000 characters.",
  urlInvalid: "Enter an HTTP(S) URL or local path, within 2,048 characters.",
  statusInvalid: "Choose a project status.",
  save: "Save Changes",
  pending: "Please wait…",
  saved: "Project updated successfully.",
  created: "Project created successfully.",
  actionError: "The action failed. Please try again.",
  deleteProject: "Delete Project",
  deleteDescription: (name: string) => `Delete ${name}? This action cannot be undone.`,
  cancel: "Cancel",
  confirmDelete: "Delete",
  deleted: "Project deleted successfully.",
};

export type ProjectsLabels = typeof projectLabels;
