export const blogsLabels = {
  blogs: "Blog posts",
  publicTitle: "Our blog",
  newPost: "New post",
  create: "Create draft",
  edit: "Edit",
  back: "Back to posts",
  categories: "Categories",
  manageCategories: "Manage categories",
  search: "Search posts",
  searchSubmit: "Search",
  allCategories: "All categories",
  popularCategories: "Categories",
  empty: "No posts found.",
  loading: "Loading…",
  retry: "Retry",
  error: "Something went wrong. Please try again.",
  title: "Title",
  slug: "Slug",
  summary: "Summary",
  language: "Language",
  languages: "Languages",
  editor: "Editor",
  modified: "Updated",
  publishedDate: "Published",
  actions: "Actions",
  draft: "Draft",
  published: "Published",
  changed: "Unpublished changes",
  missing: "Not translated",
  save: "Save draft",
  publish: "Publish",
  unpublish: "Unpublish",
  saved: "Draft saved.",
  publishedSuccess: "This language is now published.",
  unpublishedSuccess: "This language is no longer public.",
  pending: "Working…",
  delete: "Delete article",
  deleteCategory: "Delete category",
  cancel: "Cancel",
  deleteTitle: "Delete this article?",
  deleteDescription:
    "This removes every translation and publication. Its images and Markdown will be cleaned up. This cannot be undone.",
  deleteCategoryTitle: "Delete this category?",
  deleteCategoryDescription:
    "Only categories without children or article assignments can be deleted.",
  confirmDelete: "Confirm deletion",
  thumbnail: "Thumbnail",
  banner: "Banner",
  alt: "Alternative text",
  noImage: "No image",
  upload: "Upload image",
  uploading: "Uploading…",
  uploaded: "Image uploaded.",
  removeImage: "Remove image",
  shared: "Shared article settings",
  sharedHint:
    "Images and category assignments are shared. Each language captures these settings when published.",
  markdown: "Markdown",
  preview: "Preview",
  bold: "Bold",
  italic: "Italic",
  heading: "Heading",
  link: "Link",
  list: "List",
  quote: "Quote",
  code: "Code",
  insertImage: "Insert image",
  imageHint: "JPEG, PNG or WebP. Default maximum: 10 MiB.",
  readMore: "Read more",
  previous: "Previous",
  next: "Next",
  totalItems: "posts",
  readOnly: "You have read-only access.",
  newCategory: "New category",
  categoryName: "Category name",
  parent: "Parent category",
  noParent: "Main category",
  categorySaved: "Category saved.",
  categoryDeleted: "Category deleted.",
  saveCategory: "Save category",
  unsaved: "You have unsaved changes. Save before publishing or switching language.",
  addTranslation: "Add translation",
  translationHint: "Write this language version and save it as a draft.",
  required: "Complete the required fields.",
  publicationHint:
    "Publishing requires a title, slug, content, and translated names for selected categories.",
  CONFLICT:
    "This record changed or a slug is already in use. Your draft is preserved; reload the latest record before retrying.",
  INVALID: "Check your fields, image format, and file sizes.",
  FORBIDDEN: "You do not have permission to perform this action.",
  NOT_FOUND: "This record or asset is unavailable.",
  IN_USE: "This category still has children or article assignments.",
  STORAGE: "Storage is unavailable. Your draft is preserved; please retry.",
  pageLabel: (page: number, total: number) => `Page ${page} of ${total}`,
  categoryCount: (name: string, count: number) => `${name} (${count})`,
};
export type BlogsLabels = typeof blogsLabels;
