/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsRouteImport } from './routes/_blogs'
import { Route as MenusRouteImport } from './routes/_menus'
import { Route as PluginsRouteImport } from './routes/_plugins'
import { Route as CookieBannerRouteImport } from './routes/cookie-banner'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LocaleAccessDeniedRouteImport } from './routes/$locale.access-denied'
import { Route as LocaleAuthRouteImport } from './routes/$locale.auth'
import { Route as LocaleChangePasswordRouteImport } from './routes/$locale.change-password'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleEmployeesRouteImport } from './routes/$locale.employees'
import { Route as LocaleFaqRouteImport } from './routes/$locale.faq'
import { Route as LocaleForgotPasswordRouteImport } from './routes/$locale.forgot-password'
import { Route as LocaleIntranetRouteImport } from './routes/$locale.intranet'
import { Route as LocaleIntranetSidebarRouteImport } from './routes/$locale.intranet-sidebar'
import { Route as LocaleLoginRouteImport } from './routes/$locale.login'
import { Route as LocaleResetPasswordRouteImport } from './routes/$locale.reset-password'
import { Route as LocaleLegalDocumentRouteImport } from './routes/$locale.legal.$document'
import { Route as BlogsLocaleBlogsSplatRouteImport } from './routes/_blogs.$locale.blogs.$'
import { Route as MenusLocaleMenusSplatRouteImport } from './routes/_menus.$locale.menus.$'
import { Route as PluginsLocaleCustomersSplatRouteImport } from './routes/_plugins.$locale.customers.$'
import { Route as PluginsLocaleDriveSplatRouteImport } from './routes/_plugins.$locale.drive.$'
import { Route as PluginsLocaleProjectsSplatRouteImport } from './routes/_plugins.$locale.projects.$'
import { Route as BlogsLocaleAdminBlogsSplatRouteImport } from './routes/_blogs.$locale.admin.blogs.$'
import { Route as MenusLocaleAdminMenusSplatRouteImport } from './routes/_menus.$locale.admin.menus.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/_blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusRoute = MenusRouteImport.update({
  id: '/_menus',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/_plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieBannerRoute = CookieBannerRouteImport.update({
  id: '/cookie-banner',
  path: '/cookie-banner',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAccessDeniedRoute = LocaleAccessDeniedRouteImport.update({
  id: '/$locale/access-denied',
  path: '/$locale/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAuthRoute = LocaleAuthRouteImport.update({
  id: '/$locale/auth',
  path: '/$locale/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleChangePasswordRoute = LocaleChangePasswordRouteImport.update({
  id: '/$locale/change-password',
  path: '/$locale/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/$locale/contact',
  path: '/$locale/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleEmployeesRoute = LocaleEmployeesRouteImport.update({
  id: '/$locale/employees',
  path: '/$locale/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/$locale/faq',
  path: '/$locale/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleForgotPasswordRoute = LocaleForgotPasswordRouteImport.update({
  id: '/$locale/forgot-password',
  path: '/$locale/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIntranetRoute = LocaleIntranetRouteImport.update({
  id: '/$locale/intranet',
  path: '/$locale/intranet',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIntranetSidebarRoute = LocaleIntranetSidebarRouteImport.update({
  id: '/$locale/intranet-sidebar',
  path: '/$locale/intranet-sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/$locale/login',
  path: '/$locale/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleResetPasswordRoute = LocaleResetPasswordRouteImport.update({
  id: '/$locale/reset-password',
  path: '/$locale/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleLegalDocumentRoute = LocaleLegalDocumentRouteImport.update({
  id: '/$locale/legal/$document',
  path: '/$locale/legal/$document',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsLocaleBlogsSplatRoute = BlogsLocaleBlogsSplatRouteImport.update({
  id: '/$locale/blogs/$',
  path: '/$locale/blogs/$',
  getParentRoute: () => BlogsRoute,
} as any)
const MenusLocaleMenusSplatRoute = MenusLocaleMenusSplatRouteImport.update({
  id: '/$locale/menus/$',
  path: '/$locale/menus/$',
  getParentRoute: () => MenusRoute,
} as any)
const PluginsLocaleCustomersSplatRoute =
  PluginsLocaleCustomersSplatRouteImport.update({
    id: '/$locale/customers/$',
    path: '/$locale/customers/$',
    getParentRoute: () => PluginsRoute,
  } as any)
const PluginsLocaleDriveSplatRoute = PluginsLocaleDriveSplatRouteImport.update({
  id: '/$locale/drive/$',
  path: '/$locale/drive/$',
  getParentRoute: () => PluginsRoute,
} as any)
const PluginsLocaleProjectsSplatRoute =
  PluginsLocaleProjectsSplatRouteImport.update({
    id: '/$locale/projects/$',
    path: '/$locale/projects/$',
    getParentRoute: () => PluginsRoute,
  } as any)
const BlogsLocaleAdminBlogsSplatRoute =
  BlogsLocaleAdminBlogsSplatRouteImport.update({
    id: '/$locale/admin/blogs/$',
    path: '/$locale/admin/blogs/$',
    getParentRoute: () => BlogsRoute,
  } as any)
const MenusLocaleAdminMenusSplatRoute =
  MenusLocaleAdminMenusSplatRouteImport.update({
    id: '/$locale/admin/menus/$',
    path: '/$locale/admin/menus/$',
    getParentRoute: () => MenusRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie-banner': typeof CookieBannerRoute
  '/newsletter': typeof NewsletterRoute
  '/$locale/access-denied': typeof LocaleAccessDeniedRoute
  '/$locale/auth': typeof LocaleAuthRoute
  '/$locale/change-password': typeof LocaleChangePasswordRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/employees': typeof LocaleEmployeesRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/intranet': typeof LocaleIntranetRoute
  '/$locale/intranet-sidebar': typeof LocaleIntranetSidebarRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/legal/$document': typeof LocaleLegalDocumentRoute
  '/$locale/blogs/$': typeof BlogsLocaleBlogsSplatRoute
  '/$locale/menus/$': typeof MenusLocaleMenusSplatRoute
  '/$locale/customers/$': typeof PluginsLocaleCustomersSplatRoute
  '/$locale/drive/$': typeof PluginsLocaleDriveSplatRoute
  '/$locale/projects/$': typeof PluginsLocaleProjectsSplatRoute
  '/$locale/admin/blogs/$': typeof BlogsLocaleAdminBlogsSplatRoute
  '/$locale/admin/menus/$': typeof MenusLocaleAdminMenusSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-banner': typeof CookieBannerRoute
  '/newsletter': typeof NewsletterRoute
  '/$locale/access-denied': typeof LocaleAccessDeniedRoute
  '/$locale/auth': typeof LocaleAuthRoute
  '/$locale/change-password': typeof LocaleChangePasswordRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/employees': typeof LocaleEmployeesRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/intranet': typeof LocaleIntranetRoute
  '/$locale/intranet-sidebar': typeof LocaleIntranetSidebarRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/legal/$document': typeof LocaleLegalDocumentRoute
  '/$locale/blogs/$': typeof BlogsLocaleBlogsSplatRoute
  '/$locale/menus/$': typeof MenusLocaleMenusSplatRoute
  '/$locale/customers/$': typeof PluginsLocaleCustomersSplatRoute
  '/$locale/drive/$': typeof PluginsLocaleDriveSplatRoute
  '/$locale/projects/$': typeof PluginsLocaleProjectsSplatRoute
  '/$locale/admin/blogs/$': typeof BlogsLocaleAdminBlogsSplatRoute
  '/$locale/admin/menus/$': typeof MenusLocaleAdminMenusSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_blogs': typeof BlogsRouteWithChildren
  '/_menus': typeof MenusRouteWithChildren
  '/_plugins': typeof PluginsRouteWithChildren
  '/cookie-banner': typeof CookieBannerRoute
  '/newsletter': typeof NewsletterRoute
  '/$locale/access-denied': typeof LocaleAccessDeniedRoute
  '/$locale/auth': typeof LocaleAuthRoute
  '/$locale/change-password': typeof LocaleChangePasswordRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/employees': typeof LocaleEmployeesRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/intranet': typeof LocaleIntranetRoute
  '/$locale/intranet-sidebar': typeof LocaleIntranetSidebarRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/legal/$document': typeof LocaleLegalDocumentRoute
  '/_blogs/$locale/blogs/$': typeof BlogsLocaleBlogsSplatRoute
  '/_menus/$locale/menus/$': typeof MenusLocaleMenusSplatRoute
  '/_plugins/$locale/customers/$': typeof PluginsLocaleCustomersSplatRoute
  '/_plugins/$locale/drive/$': typeof PluginsLocaleDriveSplatRoute
  '/_plugins/$locale/projects/$': typeof PluginsLocaleProjectsSplatRoute
  '/_blogs/$locale/admin/blogs/$': typeof BlogsLocaleAdminBlogsSplatRoute
  '/_menus/$locale/admin/menus/$': typeof MenusLocaleAdminMenusSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-banner'
    | '/newsletter'
    | '/$locale/access-denied'
    | '/$locale/auth'
    | '/$locale/change-password'
    | '/$locale/contact'
    | '/$locale/employees'
    | '/$locale/faq'
    | '/$locale/forgot-password'
    | '/$locale/intranet'
    | '/$locale/intranet-sidebar'
    | '/$locale/login'
    | '/$locale/reset-password'
    | '/$locale/legal/$document'
    | '/$locale/blogs/$'
    | '/$locale/menus/$'
    | '/$locale/customers/$'
    | '/$locale/drive/$'
    | '/$locale/projects/$'
    | '/$locale/admin/blogs/$'
    | '/$locale/admin/menus/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-banner'
    | '/newsletter'
    | '/$locale/access-denied'
    | '/$locale/auth'
    | '/$locale/change-password'
    | '/$locale/contact'
    | '/$locale/employees'
    | '/$locale/faq'
    | '/$locale/forgot-password'
    | '/$locale/intranet'
    | '/$locale/intranet-sidebar'
    | '/$locale/login'
    | '/$locale/reset-password'
    | '/$locale/legal/$document'
    | '/$locale/blogs/$'
    | '/$locale/menus/$'
    | '/$locale/customers/$'
    | '/$locale/drive/$'
    | '/$locale/projects/$'
    | '/$locale/admin/blogs/$'
    | '/$locale/admin/menus/$'
  id:
    | '__root__'
    | '/'
    | '/_blogs'
    | '/_menus'
    | '/_plugins'
    | '/cookie-banner'
    | '/newsletter'
    | '/$locale/access-denied'
    | '/$locale/auth'
    | '/$locale/change-password'
    | '/$locale/contact'
    | '/$locale/employees'
    | '/$locale/faq'
    | '/$locale/forgot-password'
    | '/$locale/intranet'
    | '/$locale/intranet-sidebar'
    | '/$locale/login'
    | '/$locale/reset-password'
    | '/$locale/legal/$document'
    | '/_blogs/$locale/blogs/$'
    | '/_menus/$locale/menus/$'
    | '/_plugins/$locale/customers/$'
    | '/_plugins/$locale/drive/$'
    | '/_plugins/$locale/projects/$'
    | '/_blogs/$locale/admin/blogs/$'
    | '/_menus/$locale/admin/menus/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  MenusRoute: typeof MenusRouteWithChildren
  PluginsRoute: typeof PluginsRouteWithChildren
  CookieBannerRoute: typeof CookieBannerRoute
  NewsletterRoute: typeof NewsletterRoute
  LocaleAccessDeniedRoute: typeof LocaleAccessDeniedRoute
  LocaleAuthRoute: typeof LocaleAuthRoute
  LocaleChangePasswordRoute: typeof LocaleChangePasswordRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleEmployeesRoute: typeof LocaleEmployeesRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleForgotPasswordRoute: typeof LocaleForgotPasswordRoute
  LocaleIntranetRoute: typeof LocaleIntranetRoute
  LocaleIntranetSidebarRoute: typeof LocaleIntranetSidebarRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleResetPasswordRoute: typeof LocaleResetPasswordRoute
  LocaleLegalDocumentRoute: typeof LocaleLegalDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blogs': {
      id: '/_blogs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_menus': {
      id: '/_menus'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_plugins': {
      id: '/_plugins'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-banner': {
      id: '/cookie-banner'
      path: '/cookie-banner'
      fullPath: '/cookie-banner'
      preLoaderRoute: typeof CookieBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/access-denied': {
      id: '/$locale/access-denied'
      path: '/$locale/access-denied'
      fullPath: '/$locale/access-denied'
      preLoaderRoute: typeof LocaleAccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/auth': {
      id: '/$locale/auth'
      path: '/$locale/auth'
      fullPath: '/$locale/auth'
      preLoaderRoute: typeof LocaleAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/change-password': {
      id: '/$locale/change-password'
      path: '/$locale/change-password'
      fullPath: '/$locale/change-password'
      preLoaderRoute: typeof LocaleChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/$locale/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/employees': {
      id: '/$locale/employees'
      path: '/$locale/employees'
      fullPath: '/$locale/employees'
      preLoaderRoute: typeof LocaleEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/$locale/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/forgot-password': {
      id: '/$locale/forgot-password'
      path: '/$locale/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/intranet': {
      id: '/$locale/intranet'
      path: '/$locale/intranet'
      fullPath: '/$locale/intranet'
      preLoaderRoute: typeof LocaleIntranetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/intranet-sidebar': {
      id: '/$locale/intranet-sidebar'
      path: '/$locale/intranet-sidebar'
      fullPath: '/$locale/intranet-sidebar'
      preLoaderRoute: typeof LocaleIntranetSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/$locale/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/reset-password': {
      id: '/$locale/reset-password'
      path: '/$locale/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/legal/$document': {
      id: '/$locale/legal/$document'
      path: '/$locale/legal/$document'
      fullPath: '/$locale/legal/$document'
      preLoaderRoute: typeof LocaleLegalDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blogs/$locale/blogs/$': {
      id: '/_blogs/$locale/blogs/$'
      path: '/$locale/blogs/$'
      fullPath: '/$locale/blogs/$'
      preLoaderRoute: typeof BlogsLocaleBlogsSplatRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/_menus/$locale/menus/$': {
      id: '/_menus/$locale/menus/$'
      path: '/$locale/menus/$'
      fullPath: '/$locale/menus/$'
      preLoaderRoute: typeof MenusLocaleMenusSplatRouteImport
      parentRoute: typeof MenusRoute
    }
    '/_plugins/$locale/customers/$': {
      id: '/_plugins/$locale/customers/$'
      path: '/$locale/customers/$'
      fullPath: '/$locale/customers/$'
      preLoaderRoute: typeof PluginsLocaleCustomersSplatRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/_plugins/$locale/drive/$': {
      id: '/_plugins/$locale/drive/$'
      path: '/$locale/drive/$'
      fullPath: '/$locale/drive/$'
      preLoaderRoute: typeof PluginsLocaleDriveSplatRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/_plugins/$locale/projects/$': {
      id: '/_plugins/$locale/projects/$'
      path: '/$locale/projects/$'
      fullPath: '/$locale/projects/$'
      preLoaderRoute: typeof PluginsLocaleProjectsSplatRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/_blogs/$locale/admin/blogs/$': {
      id: '/_blogs/$locale/admin/blogs/$'
      path: '/$locale/admin/blogs/$'
      fullPath: '/$locale/admin/blogs/$'
      preLoaderRoute: typeof BlogsLocaleAdminBlogsSplatRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/_menus/$locale/admin/menus/$': {
      id: '/_menus/$locale/admin/menus/$'
      path: '/$locale/admin/menus/$'
      fullPath: '/$locale/admin/menus/$'
      preLoaderRoute: typeof MenusLocaleAdminMenusSplatRouteImport
      parentRoute: typeof MenusRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsLocaleBlogsSplatRoute: typeof BlogsLocaleBlogsSplatRoute
  BlogsLocaleAdminBlogsSplatRoute: typeof BlogsLocaleAdminBlogsSplatRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsLocaleBlogsSplatRoute: BlogsLocaleBlogsSplatRoute,
  BlogsLocaleAdminBlogsSplatRoute: BlogsLocaleAdminBlogsSplatRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface MenusRouteChildren {
  MenusLocaleMenusSplatRoute: typeof MenusLocaleMenusSplatRoute
  MenusLocaleAdminMenusSplatRoute: typeof MenusLocaleAdminMenusSplatRoute
}

const MenusRouteChildren: MenusRouteChildren = {
  MenusLocaleMenusSplatRoute: MenusLocaleMenusSplatRoute,
  MenusLocaleAdminMenusSplatRoute: MenusLocaleAdminMenusSplatRoute,
}

const MenusRouteWithChildren = MenusRoute._addFileChildren(MenusRouteChildren)

interface PluginsRouteChildren {
  PluginsLocaleCustomersSplatRoute: typeof PluginsLocaleCustomersSplatRoute
  PluginsLocaleDriveSplatRoute: typeof PluginsLocaleDriveSplatRoute
  PluginsLocaleProjectsSplatRoute: typeof PluginsLocaleProjectsSplatRoute
}

const PluginsRouteChildren: PluginsRouteChildren = {
  PluginsLocaleCustomersSplatRoute: PluginsLocaleCustomersSplatRoute,
  PluginsLocaleDriveSplatRoute: PluginsLocaleDriveSplatRoute,
  PluginsLocaleProjectsSplatRoute: PluginsLocaleProjectsSplatRoute,
}

const PluginsRouteWithChildren =
  PluginsRoute._addFileChildren(PluginsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRouteWithChildren,
  MenusRoute: MenusRouteWithChildren,
  PluginsRoute: PluginsRouteWithChildren,
  CookieBannerRoute: CookieBannerRoute,
  NewsletterRoute: NewsletterRoute,
  LocaleAccessDeniedRoute: LocaleAccessDeniedRoute,
  LocaleAuthRoute: LocaleAuthRoute,
  LocaleChangePasswordRoute: LocaleChangePasswordRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleEmployeesRoute: LocaleEmployeesRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleForgotPasswordRoute: LocaleForgotPasswordRoute,
  LocaleIntranetRoute: LocaleIntranetRoute,
  LocaleIntranetSidebarRoute: LocaleIntranetSidebarRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleResetPasswordRoute: LocaleResetPasswordRoute,
  LocaleLegalDocumentRoute: LocaleLegalDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
