export const customerLabels = {
  title: "Customers",
  description: "Manage your customers and their contact details.",
  customer: "Customer",
  actions: "Actions",
  search: "Search customers",
  searchPlaceholder: "Search customers...",
  loading: "Loading customers...",
  empty: "No customers found.",
  create: "Create Customer",
  newTitle: "New Customer",
  newDescription: "Add a customer and their contact details.",
  back: "Back to Customers",
  edit: "Edit customer details",
  viewProjects: "View customer projects",
  sections: "Customer sections",
  about: "About",
  projects: "Projects",
  sync: "Sync",
  verified: "Verified",
  unverified: "Unverified",
  banned: "Banned",
  yes: "Yes",
  verify: "Verify customer",
  unverify: "Unverify customer",
  impersonate: "Impersonate customer",
  contactTitle: "Contact person",
  contactDescription: "The primary person to contact about this customer.",
  name: "Full name",
  email: "Email",
  phoneNumber: "Phone Number",
  phonePlaceholder: "e.g. +41 79 123 45 67",
  companyTitle: "Company",
  companyDescription: "Optional. Leave empty for an individual customer.",
  companyName: "Company name",
  billingTitle: "Billing address",
  street: "Street",
  streetPlaceholder: "e.g. Bahnhofstrasse 1",
  city: "NPA & City",
  cityPlaceholder: "e.g. 8000 Zurich",
  addressComplement: "Address Complement",
  addressPlaceholder: "e.g. Apartment 4B",
  password: "Temporary password",
  passwordDescription: (min: number, max: number) => `Optional. Use ${min}–${max} characters.`,
  generatePassword: "Generate and copy a strong password",
  copyPassword: "Copy password",
  passwordCopied: "Password copied.",
  passwordCopyError: "Could not copy the password. Copy it manually.",
  passwordGenerateError: "Could not generate a password. Enter one manually.",
  nameRequired: "Enter a full name.",
  emailRequired: "Enter a valid email address.",
  passwordInvalid: (min: number, max: number) => `Use ${min}–${max} characters.`,
  save: "Save Changes",
  pending: "Please wait...",
  saved: "Customer updated successfully.",
  created: "Customer created successfully.",
  actionSuccess: "Customer action completed successfully.",
  actionError: "The action failed. Please try again.",
  deleteCustomer: "Delete Customer",
  deleteDescription: (name: string) =>
    `Are you sure you want to delete ${name}? This action cannot be undone.`,
  cancel: "Cancel",
  confirmDelete: "Delete",
  deleted: "Customer deleted successfully.",
};

export type CustomersLabels = typeof customerLabels;
